apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kabaflaskdep
  name: kabaflaskdep
  namespace: kaba-shiba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kabaflaskdep
  template:
    metadata:
      labels:
        app: kabaflaskdep
    spec:
      containers:
      - image: shomaigu/kabafla:latest
        name: kabaflaskdep
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kabadb
  name: kabadb
  namespace: kaba-shiba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kabadb
  template:
    metadata:
      labels:
        app: kabadb
    spec:
      containers:
      - image: mariadb
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "tmcit"
        - name: MARIADB_DATABASE
          value: "ques"
        - name: MARIADB_USER
          value: "docker"
        - name: MARIADB_PASSWORD
          value: "docker"
