apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskdep
  name: flaskserv
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskdep
  type: NodePort
status:
