version: '3'

services:
  flask:
    container_name: flaskkaba
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    volumes: 
      - ./app/pyapp:/usr/src/app/
      - ./app/pyapp/templates:/usr/src/app/templates
    restart: always
    tty: true


  db:
    restart: always
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    container_name: mariadbkaba
    environment:
      MARIADB_ROOT_PASSWORD: tmcit
      MARIADB_DATABASE: ques
      MARIADB_USER: tmcit
      MARIADB_PASSWORD: tmcit
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
