apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kaba_flaskdep
  name: kaba_flaskdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaba_flaskdep
  template:
    metadata:
      labels:
        app: kaba_flaskdep
    spec:
      containers:
      - image: shomaigu/iwa_fla:latest
        name: kaba_flaskdep
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kaba_db
  name: kaba_db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaba_db
  template:
    metadata:
      labels:
        app: kaba_db
    spec:
      containers:
      - image: mariadb
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "tmcit"
        - name: MARIADB_DATABASE
          value: "ques"
        - name: MARIADB_USER
          value: "docker"
        - name: MARIADB_PASSWORD
          value: "docker"
