apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskdep
  name: flaskserv
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskdep
  type: NodePort
status:

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
  type: NodePort
status:
